language: generic
# safelist
branches:
  only:
  - dev
cache:
  directories:
    - "VueJS/node_modules"
before_install:
  - cd ..
install:
  - cd VueJS
  - npm install
  - cd ../Backend
  - npm install
script:
  - npm run lint
  - npm run test
  - cd ../Backend
  - npm test
after_success:
  - npm run build