language: node_js
# safelist
branches:
  only:
  - dev
cache:
  directories:
    - "2/node_modules"
before_install:
  - cd "2"
install:
  - npm install
script:
  - npm run lint
  - npm run test
after_success:
  - npm run build