# safelist
branches:
  only:
  - dev
cache:
  directories:
    - "2/node_modules"
install:
  - npm install
before_script:
  - cd "2"
script:
  - npm run lint
  - npm run test
after_success:
  - npm run build