language: generic
# safelist
branches:
  only:
  - dev
install:
  - cd VueJS
  - npm install
  - cd ../Backend
  - npm install
before-script:
  - cd ..
script:
  - cd VueJs
  - npm run lint
  - npm run test
  - cd ../Backend
  - npm test
after_success:
  - cd VueJS
  - npm run build