language: generic

jdk:
  - oraclejdk8

env:
  - NEO4J_VERSION="3.5.12"

branches:
  - dev_5_full

services:
  - neo4j

before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - sleep 10
  - curl -v POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=neo4j2"
  - curl -v POST http://neo4j:neo4j2@localhost:7474/user/neo4j/password -d"password=neo4j"

install:
  - cd VueJS
  - npm install
  - cd ../Backend
  - yarn install

script:
  - cd ../VueJS
  - npm run lint
  - npm run test
  - cd ../Backend
  - yarn run db:reset
  - yarn run db:seed
  - yarn run test

after_success:
  - cd ../Backend
  - yarn run start
  - cd ../VueJS
  - npm run build