language: generic
# safelist
branches:
  only:
  - dev
cache:
  directories:
    - "VueJS/node_modules"
before_install:
  - cd "VueJS"
install:
  - npm install
script:
  - npm run lint
  - npm run test
after_success:
  - npm run build