query getJahr($number: Int!, $userId: ID!) {
  getJahr(number: $number, userId: $userId) {
    number
    months {
      number
      days {
        day
        work
        duration
      }
    }
  }
}